version: '3.9'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    volumes:
      - pg:/data/postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: food_order_dev
volumes:
  pg:
    driver: local
